{
  description = "AgentProlog standalone coding-agent product";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    prolog-rlm = {
      # #141 packaging landed through prolog-rlm#145. Keep the product pinned to
      # the exact reviewed runtime commit; flake.lock remains the transitive
      # dependency authority once generated by Nix.
      url = "github:lost-rob0t/prolog-rlm/c0a7484d71265eed1a0f96f012040db39d9e58f1";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, flake-utils, prolog-rlm }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
        upstream = prolog-rlm.packages.${system}.default;
        upstreamSwipl = "${upstream}/bin/prolog-rlm-swipl";
        agentProlog = pkgs.writeShellApplication {
          name = "agentProlog";
          runtimeInputs = [ upstream ];
          text = ''
            exec ${upstreamSwipl} -q -g "use_module(library(rlm)),writeln('AgentProlog runtime ready'),halt" -- "$@"
          '';
        };
      in {
        packages.agentProlog = agentProlog;
        packages.default = agentProlog;

        apps.agentProlog = flake-utils.lib.mkApp { drv = agentProlog; };
        apps.default = self.apps.${system}.agentProlog;

        devShells.default = pkgs.mkShell {
          packages = [ upstream ];
        };

        checks.runtime-load = pkgs.runCommand "agentprolog-runtime-load" {
          nativeBuildInputs = [ upstream ];
        } ''
          export HOME="$TMPDIR/home"
          mkdir -p "$HOME"
          cd "$TMPDIR"
          ${upstreamSwipl} -q -g "use_module(library(rlm)),halt"
          touch "$out"
        '';

        checks.default-app = pkgs.runCommand "agentprolog-default-app" {
          nativeBuildInputs = [ agentProlog ];
        } ''
          agentProlog | grep -F "AgentProlog runtime ready"
          touch "$out"
        '';
      });
}
